CREATE DATABASE LARISA_POBOL;
GO

USE LARISA_POBOL;
GO

CREATE SCHEMA sales;
GO

CREATE SCHEMA persons;
GO

CREATE TABLE sales.Orders (OrderNum INT NULL);
GO

BACKUP DATABASE LARISA_POBOL TO DISK='D:\LARISA_POBOL.bak';

USE MASTER;
DROP DATABASE LARISA_POBOL;

RESTORE DATABASE LARISA_POBOL FROM DISK='D:\LARISA_POBOL.bak';